In [29]:
 import numpy as np
 import pandas as pd
 import difflib
 from sklearn.feature_extraction.text import TfidfVectorizer
 from sklearn.metrics.pairwise import cosine_similarity

In [30]:
# importing dependents
# reading data
# data shape
# selecting features
# vectorizer
# similarity
# input data
# # indexing

In [31]:
data=pd.read_csv("movies.csv")

In [32]:
data.head()

index     budget                                    genres  \
0      0  237000000  Action Adventure Fantasy Science Fiction   
1      1  300000000                  Adventure Fantasy Action   
2      2  245000000                    Action Adventure Crime   
3      3  250000000               Action Crime Drama Thriller   
4      4  260000000          Action Adventure Science Fiction   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   
1  ocean drug abuse exotic island east india trad...                en   
2         spy based on novel secret agent sequel mi6                en   
3  dc comics crime fighter terrorist secret ident...                en   
4  based on novel mars medallion space travel pri...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  ... runtime  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577  ...   162.0   
1  Captain Barbossa, long believed to be dead, ha...  139.082615  ...   169.0   
2  A cryptic message from Bond’s past sends him o...  107.376788  ...   148.0   
3  Following the death of District Attorney Harve...  112.312950  ...   165.0   
4  John Carter is a war-weary, former military ca...   43.926995  ...   132.0   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3           [{"iso_639_1": "en", "name": "English"}]  Released   
4           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title vote_average vote_count  \
0                                    Avatar          7.2      11800   
1  Pirates of the Caribbean: At World's End          6.9       4500   
2                                   Spectre          6.3       4466   
3                     The Dark Knight Rises          7.6       9106   
4                               John Carter          6.1       2124   

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...   
1  Johnny Depp Orlando Bloom Keira Knightley Stel...   
2  Daniel Craig Christoph Waltz L\u00e9a Seydoux ...   
3  Christian Bale Michael Caine Gary Oldman Anne ...   
4  Taylor Kitsch Lynn Collins Samantha Morton Wil...   

                                                crew           director  
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron  
1  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski  
2  [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes  
3  [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan  
4  [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton  

[5 rows x 24 columns]

In [33]:
data.shape

(4803, 24)

In [34]:

selected_features = ['genres','keywords','tagline','cast','crew','director']
print(selected_features)

['genres', 'keywords', 'tagline', 'cast', 'crew', 'director']


In [35]:
for features in selected_features:
  data[features] = data[features].fillna('')

In [36]:
combined_features = data['genres']+' '+data['keywords']+' '+data['tagline']+' '+data['cast']+' '+data['crew']+' '+data['director']
print(combined_features)

0       Action Adventure Fantasy Science Fiction cultu...
1       Adventure Fantasy Action ocean drug abuse exot...
2       Action Adventure Crime spy based on novel secr...
3       Action Crime Drama Thriller dc comics crime fi...
4       Action Adventure Science Fiction based on nove...
                              ...                        
4798    Action Crime Thriller united states\u2013mexic...
4799    Comedy Romance  A newlywed couple's honeymoon ...
4800    Comedy Drama Romance TV Movie date love at fir...
4801      A New Yorker in Shanghai Daniel Henney Eliza...
4802    Documentary obsession camcorder crush dream gi...
Length: 4803, dtype: object


In [37]:
feature_vector = TfidfVectorizer()

In [38]:
vector = feature_vector.fit_transform(combined_features)

In [39]:
print(vector)

  (0, 29019)	0.01790707456721377
  (0, 143280)	0.01790707456721377
  (0, 225296)	0.01790707456721377
  (0, 209158)	0.014091240819006496
  (0, 20863)	0.01790707456721377
  (0, 113856)	0.01790707456721377
  (0, 186017)	0.006916327761182138
  (0, 20862)	0.01708049820015306
  (0, 113855)	0.01790707456721377
  (0, 224871)	0.01708049820015306
  (0, 20861)	0.01790707456721377
  (0, 113854)	0.01790707456721377
  (0, 220647)	0.01790707456721377
  (0, 20860)	0.01708049820015306
  (0, 113852)	0.01790707456721377
  (0, 214704)	0.01708049820015306
  (0, 212902)	0.009832607751541907
  (0, 20859)	0.01790707456721377
  (0, 113850)	0.01790707456721377
  (0, 210706)	0.01790707456721377
  (0, 217608)	0.014091240819006496
  (0, 20858)	0.01790707456721377
  (0, 113847)	0.01790707456721377
  (0, 208711)	0.016039135133762216
  (0, 207885)	0.01292813482806752
  :	:
  (4802, 195609)	0.11579430580983312
  (4802, 211288)	0.11289050108812473
  (4802, 193683)	0.09546589850840864
  (4802, 212784)	0.1034498413284588

In [40]:
similarity = cosine_similarity(vector)

In [41]:
print(similarity)

[[1.         0.57678646 0.82520836 ... 0.36414831 0.08699279 0.20460576]
 [0.57678646 1.         0.58274682 ... 0.32880209 0.0753864  0.18034924]
 [0.82520836 0.58274682 1.         ... 0.38178127 0.09709008 0.20802944]
 ...
 [0.36414831 0.32880209 0.38178127 ... 1.         0.05206672 0.1312928 ]
 [0.08699279 0.0753864  0.09709008 ... 0.05206672 1.         0.0309998 ]
 [0.20460576 0.18034924 0.20802944 ... 0.1312928  0.0309998  1.        ]]


In [42]:
similarity.shape

(4803, 4803)

In [43]:
movie_input = input('Enter the movie : \n')

Enter the movie : 
batman


In [44]:
list_of_movies = data['title'].tolist()

In [45]:
print(list_of_movies)

['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre', 'The Dark Knight Rises', 'John Carter', 'Spider-Man 3', 'Tangled', 'Avengers: Age of Ultron', 'Harry Potter and the Half-Blood Prince', 'Batman v Superman: Dawn of Justice', 'Superman Returns', 'Quantum of Solace', "Pirates of the Caribbean: Dead Man's Chest", 'The Lone Ranger', 'Man of Steel', 'The Chronicles of Narnia: Prince Caspian', 'The Avengers', 'Pirates of the Caribbean: On Stranger Tides', 'Men in Black 3', 'The Hobbit: The Battle of the Five Armies', 'The Amazing Spider-Man', 'Robin Hood', 'The Hobbit: The Desolation of Smaug', 'The Golden Compass', 'King Kong', 'Titanic', 'Captain America: Civil War', 'Battleship', 'Jurassic World', 'Skyfall', 'Spider-Man 2', 'Iron Man 3', 'Alice in Wonderland', 'X-Men: The Last Stand', 'Monsters University', 'Transformers: Revenge of the Fallen', 'Transformers: Age of Extinction', 'Oz: The Great and Powerful', 'The Amazing Spider-Man 2', 'TRON: Legacy', 'Cars 2', 'Green Lant

In [46]:
find_close_match = difflib.get_close_matches(movie_input,list_of_movies)
print(find_close_match)

['Batman', 'Batman', 'Catwoman']


In [47]:
close_match = find_close_match[0]
print(close_match)

Batman


In [48]:
index_of_the_movie = data[data.title == close_match]['index'].values[0]
print(index_of_the_movie)

1359


In [49]:
similarity_score = list(enumerate(similarity[index_of_the_movie]))
print(similarity_score)

[(0, 0.3621800408062683), (1, 0.3313927165399785), (2, 0.37612719277210166), (3, 0.4051076984472843), (4, 0.38204444002468546), (5, 0.3670904151160327), (6, 0.331223977987781), (7, 0.37921919273118443), (8, 0.3017603749417896), (9, 0.40629083233202734), (10, 0.33950321585891374), (11, 0.27018240521787074), (12, 0.2975444876741551), (13, 0.31869765950816353), (14, 0.36876746392391), (15, 0.37452620845634194), (16, 0.3620582427120215), (17, 0.3330466487753436), (18, 0.30083837772492644), (19, 0.3782652713261321), (20, 0.36678096965294027), (21, 0.2584096624624004), (22, 0.37875230049634545), (23, 0.323385625117398), (24, 0.3240986498363325), (25, 0.34887118857429467), (26, 0.3788014662627085), (27, 0.37277927502627517), (28, 0.3948732206719307), (29, 0.31690046581295417), (30, 0.4047074047480742), (31, 0.3215955766366077), (32, 0.3423120559498421), (33, 0.33930102715186294), (34, 0.23096472740358365), (35, 0.36387035508159504), (36, 0.36400650969624343), (37, 0.3212778992421236), (38, 0.

In [50]:
sorted_data = sorted(similarity_score,key = lambda x:x[1],reverse = True)
print(sorted_data)

[(1359, 0.9999999999999997), (428, 0.4506520907756402), (303, 0.411828989481572), (119, 0.41137138506557147), (210, 0.4077169955417304), (165, 0.40711950279110115), (408, 0.40693565668256476), (9, 0.40629083233202734), (291, 0.4056657987608039), (386, 0.4056122998253642), (186, 0.4051980053511327), (3, 0.4051076984472843), (65, 0.40470839573543305), (30, 0.4047074047480742), (112, 0.4044847008399485), (93, 0.404275555906796), (320, 0.40400416970247527), (275, 0.4028145783144081), (673, 0.4025095679003049), (583, 0.40178539590473483), (150, 0.4014523664089747), (276, 0.40137730421451495), (182, 0.40132259056431496), (197, 0.40128404401930595), (529, 0.40112461882485473), (250, 0.40061101523203235), (164, 0.4005650231267476), (191, 0.4005262334930368), (935, 0.4004459109829961), (180, 0.4003711024029555), (505, 0.4001252564717685), (117, 0.3999711744221166), (223, 0.399598271891864), (263, 0.39948244635337216), (185, 0.3994604730862183), (828, 0.3994346561164182), (171, 0.399265465008436

In [53]:
print("The recommended movies for you: \n")

i = 1

for movie in sorted_data:
  index = movie[0]
  title_of_the_movie = data[data.index==index]['title'].values[0]
  if (i<31):
    print(i,'.',title_of_the_movie)
    i+=1

The recommended movies for you: 

1 . Batman
2 . Batman Returns
3 . Catwoman
4 . Batman Begins
5 . Batman & Robin
6 . Hulk
7 . Collateral Damage
8 . Batman v Superman: Dawn of Justice
9 . National Treasure
10 . The Bourne Supremacy
11 . Bad Boys II
12 . The Dark Knight Rises
13 . The Dark Knight
14 . Spider-Man 2
15 . Alexander
16 . Terminator 3: Rise of the Machines
17 . Black Hawk Down
18 . Minority Report
19 . Austin Powers in Goldmember
20 . Big Fish
21 . Men in Black II
22 . Harry Potter and the Chamber of Secrets
23 . Ant-Man
24 . Harry Potter and the Philosopher's Stone
25 . Tears of the Sun
26 . The Aviator
27 . Lethal Weapon 4
28 . Harry Potter and the Prisoner of Azkaban
29 . Herbie Fully Loaded
30 . The Bourne Ultimatum
